language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install configparser backports.functools_lru_cache; fi
# command to run tests
script: pytest
