[build-system]
requires = ["flit_core >=2,<5"]
build-backend = "flit_core.buildapi"

[project]
name = "entrypoints"
authors = [
    { name = "Thomas Kluyver", email = "thomas@kluyver.me.uk" },
]
readme = "README.rst"
license = "MIT"
requires-python = ">=3.6"
dynamic = ["version", "description"]
classifiers = [
    "Programming Language :: Python :: 3"
]

[project.urls]
Homepage = "https://github.com/takluyver/entrypoints"
Documentation = "https://entrypoints.readthedocs.io/en/latest/"
